package com.example.realestate.feature.home

import com.example.realestate.core.model.Property


fun sampleProperties(): List<Property> = listOf(
    Property(
        type = "Apartment",
        title = "Royal Apartment",
        address = "LosAngles LA",
        pickPath = "pic_1",
        price = 1500,
        bed = 2,
        bath = 3,
        size = 350,
        isGarage = true,
        score = 4.5,
        description = "This 2 bed /1 bath home boasts an enormous, open-living plan..."
    ),
    Property(
        type = "House",
        title = "House with Great View",
        address = "Newyork NY",
        pickPath = "pic_2",
        price = 800,
        bed = 1,
        bath = 2,
        size = 500,
        isGarage = false,
        score = 4.9,
        description = "This 2 bed /1 bath home boasts an enormous, open-living plan..."
    ),
    Property(
        type = "Villa",
        title = "Royal Villa",
        address = "LosAngles La",
        pickPath = "pic_3",
        price = 999,
        bed = 2,
        bath = 1,
        size = 400,
        isGarage = true,
        score = 4.7,
        description = "This 2 bed /1 bath home boasts an enormous, open-living plan..."
    ),
    Property(
        type = "House",
        title = "beauty house",
        address = "Newyork NY",
        pickPath = "pic_4",
        price = 1750,
        bed = 3,
        bath = 2,
        size = 1100,
        isGarage = true,
        score = 4.3,
        description = "This 2 bed /1 bath home boasts an enormous, open-living plan..."
    ),
    Property(
        type = "Condo",
        title = "Riverside Condo",
        address = "Portland, OR",
        pickPath = "pic_1",
        price = 1900,
        bed = 2,
        bath = 2,
        size = 1000,
        isGarage = false,
        score = 4.2,
        description = "Condo with scenic river views, balcony, and nearby parks..."
    ),
    Property(
        type = "House",
        title = "Meadowbrook House",
        address = "Austin, TX",
        pickPath = "pic_2",
        price = 2600,
        bed = 4,
        bath = 3,
        size = 2100,
        isGarage = true,
        score = 4.4,
        description = "Modern family house with open kitchen, patio, and spacious garage..."
    ),
    Property(
        type = "Apartment",
        title = "Harbor View Apartment",
        address = "Seattle, WA",
        pickPath = "pic_3",
        price = 1750,
        bed = 2,
        bath = 1,
        size = 800,
        isGarage = false,
        score = 4.0,
        description = "Waterfront apartment offering a stunning harbor view and cozy living..."
    ),
    Property(
        type = "Villa",
        title = "Palm Villa",
        address = "Orlando, FL",
        pickPath = "pic_4",
        price = 3500,
        bed = 5,
        bath = 4,
        size = 2800,
        isGarage = true,
        score = 4.6,
        description = "Spacious villa near theme parks with private pool and large backyard..."
    ),
    Property(
        type = "Penthouse",
        title = "Elite Penthouse",
        address = "Los Angeles, CA",
        pickPath = "pic_1",
        price = 4500,
        bed = 4,
        bath = 4,
        size = 3000,
        isGarage = true,
        score = 4.9,
        description = "Exclusive penthouse with panoramic city views and luxury amenities..."
    ),
    Property(
        type = "Apartment",
        title = "Central Park Apartment",
        address = "Chicago, IL",
        pickPath = "pic_2",
        price = 2000,
        bed = 2,
        bath = 1,
        size = 950,
        isGarage = false,
        score = 4.1,
        description = "Apartment close to central park with modern design and city view..."
    ),
    Property(
        type = "House",
        title = "Oakwood House",
        address = "Dallas, TX",
        pickPath = "pic_3",
        price = 2200,
        bed = 3,
        bath = 3,
        size = 1850,
        isGarage = true,
        score = 4.3,
        description = "Spacious family home with backyard garden and two-car garage..."
    ),
    Property(
        type = "Condo",
        title = "Skyline Condo",
        address = "New York, NY",
        pickPath = "pic_4",
        price = 2700,
        bed = 3,
        bath = 2,
        size = 1250,
        isGarage = true,
        score = 4.7,
        description = "Stylish condo with skyline views, rooftop access, and fitness center..."
    ),
    Property(
        type = "Apartment",
        title = "Greenwood Residency",
        address = "San Francisco, CA",
        pickPath = "pic_1",
        price = 1800,
        bed = 2,
        bath = 2,
        size = 900,
        isGarage = false,
        score = 4.2,
        description = "Modern apartment located in the heart of the city, near downtown..."
    ),
    Property(
        type = "Villa",
        title = "Sunset Villa",
        address = "Miami Beach, FL",
        pickPath = "pic_2",
        price = 3200,
        bed = 4,
        bath = 3,
        size = 2100,
        isGarage = true,
        score = 4.8,
        description = "Luxury villa with private pool, sea view, and modern interiors..."
    )
)
